sudo: required

language: ruby

rvm:
  - 2.2.5
  - 2.3.0

services:
  - docker

before_install:
  - docker pull openfrontier/gerrit
  - ssh-keygen -b 2048 -t rsa -q -N ""

script:
  - bundle exec rake test
