sudo: required

language: ruby

rvm:
  - 2.2.5
  - 2.3.1

services:
  - docker

before_install:
  - docker pull openfrontier/gerrit:latest
  - ssh-keygen -b 2048 -t rsa -q -N "" -f /home/travis/.ssh/id_rsa
  - docker run -d -P --env AUTH_TYPE=DEVELOPMENT_BECOME_ANY_ACCOUNT --name gerrit openfrontier/gerrit:latest

env:
  - GERRIT_SKIP_TEARDOWN=true GERRIT_CONTAINER_ID=gerrit

script:
  - bundle exec rake test

