#!/usr/bin/env ruby

require 'ap'
require 'colored'
require 'optparse'

$LOAD_PATH << File.expand_path(File.join(File.dirname(__FILE__), 'src'))
require 'git-sync'

dry_run = false

OptionParser.new do |opts|
  opts.banner = "Usage: git-sync [@options] <config.yml>"

  opts.on("-n", "--dry-run", "Do not perform actual sync") do
    dry_run = true
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

config_path = ARGV[0]

if not config_path or not File.exists? config_path
  puts "Config file doesn't exist"
  exit 1
end

puts "Loading config #{config_path} ...".blue
config = GitSync::Config.new
config.load_from_file config_path

puts "Scheduling tasks ...".blue
tasks = []
config.sources.each { |src| tasks += src.schedule }

puts "Performing syncs ...".blue
tasks.each do |task|
  task.sync!(dry_run)
end
