#!/bin/sh

SYNC_USER=${SYNC_USER:-gitsync}
SYNC_UID=${SYNC_UID:-1000}
SYNC_GROUP=${SYNC_GROUP:-gitsync}
SYNC_GID=${SYNC_GID:-1000}
SYNC_HOME=${SYNC_HOME:-/home/$SYNC_USER}

set -e

if ! id $SYNC_USER > /dev/null 2>&1; then
    if id $SYNC_UID > /dev/null 2>&1; then
        deluser $SYNC_UID
    fi

    groupadd --gid $SYNC_GID $SYNC_GROUP
    useradd --home "$SYNC_HOME" --uid $SYNC_UID --gid $SYNC_GID --shell /bin/sh $SYNC_USER

    if [ -e "$SYNC_HOME/.ssh" ]; then
        chown -R $SYNC_UID:$SYNC_GID $SYNC_HOME/.ssh
    fi
fi

cd /usr/src/app
su -c "bundle exec ./git-sync $*" $SYNC_USER

